### ISSUE TITLE
Security software with malware?

### ISSUE THREAD

**Issue by rfaix** [oocx/acme.net#16]
Isn't it nice to get security software with malware combined?
![screenshot 2017-03-22 15 42 25](https://cloud.githubusercontent.com/assets/19901712/24187081/5d05ed74-0f16-11e7-843f-93368422499b.png)

**Comment by oocx** [comment]
Which file / release did you scan?

**Comment by rfaix** [comment]
The newest one 0.0.65 <https://github.com/oocx/acme.net/releases/tag/0.0.65>

best regards
Rudolf Faix
Affiliate Marketing Reviews <http://affiliates.wwpa.com/>
Fraud & Scam Systems <http://fraud-systems.wwpa.com/>
Offshore Outsourcing & Scammer <http://blog.wwpa.com/>

**Comment by oocx** [comment]
Thanks for reporting this.

I'm currently at work, but I will look into this issue when I'm back home.

Releases are build on AppVeyor and published from there to GitHub automatically. If it really contains malware and is not just a false positive, then AppVeyor has a problem with their build servers.

**Comment by rfaix** [comment]
Where ever the Malware has been coming inside, it needs to get removed. 😂
It can be a problem from the hosting provider too. I had today a second
case too.

best regards
Rudolf Faix
Affiliate Marketing Reviews <http://affiliates.wwpa.com/>
Fraud & Scam Systems <http://fraud-systems.wwpa.com/>
Offshore Outsourcing & Scammer <http://blog.wwpa.com/>

**Comment by mj2015** [comment]
I have run that file through VirusTotal.com and it has a score of 2/60 vendors showing it as bad. Given the age of the file, I suspect it is simply a false alarm, and you should contact the virus vendor to tell them.

https://virustotal.com/en-gb/file/8c3c0be2bd3eb6e35bc8c305a3232675d2d7d885802f2c37654bb5ee7598f1fa/analysis/1490175678/

**Comment by oocx** [comment]
I have analyzed the file with metadefender and VirSCAN.org. Metadefender found nothing (0/40), VirSCAN.org 1 out of 39. I assume that that's a heuristic scan reporting a false positive.

**Comment by rfaix** [comment]
Bitdefender and Avira are the engines, which are saying it is malware.
Nobody will take the risk and turn off his virus engine for installing a
software. With other words, it does not help anybody to say it is a false
positive.

best regards
Rudolf Faix
Affiliate Marketing Reviews <http://affiliates.wwpa.com/>
Fraud & Scam Systems <http://fraud-systems.wwpa.com/>
Offshore Outsourcing & Scammer <http://blog.wwpa.com/>

**Comment by oocx** [comment]
So it's a problem with Avira and Bitdefender, not with the .exe here. You should report the problem to them if you care about it.

This is not a commercial product and not even an open source project that was created to be used in production. I clearly state in the readme "I created this project as a training excercise". I posted it to Github so that others can use my code if it is useful to them. There are other acme clients that were actually created to be used in production environments. If my project does not work for you, you can either modify it and submit a pull request, fork it and work on your own branch, or simply use one of the other clients.
